feat(tablekit-react): add radio component
tablecheck/tablekit pull request #122
Opened 2022-09-21 12:55 UTC by staevs

Resolves https://github.com/tablecheck/tablekit/issues/106

2022-09-25 23:51 UTC, wahidfarid approved these changes

2022-09-25 23:55 UTC, gazpachu commented on system/react/src/components/Radio.ts
> +  --radio-size: 21px;
A bit odd number

2022-09-26 01:19 UTC, SimeonC requested changes
![CleanShot 2022-09-26 at 10 18 36](https://user-images.githubusercontent.com/1085899/192175949-5f4d1160-10ad-4f40-8561-97c176448893.png)

Looks like we have some weird centering issues of the dot, I think this may be because of the 21px that @gazpachu pointed out.

2022-09-26 01:19 UTC, SimeonC commented on system/react/src/components/Radio.ts
> +export const Radio = styled.input<{ type?: 'radio' }>`
This should be required.
```suggestion
export const Radio = styled.input<{ type: 'radio' }>`
```

2022-09-26 05:02 UTC, staevs commented on system/react/src/components/Radio.ts
> +export const Radio = styled.input<{ type?: 'radio' }>`
Why, it's set from default props, so always would be radio?

2022-09-26 05:03 UTC, staevs commented on system/react/src/components/Radio.ts
> +  --radio-size: 21px;
That's from figma

2022-09-26 08:11 UTC, staevs commented
> #106

wierd, where did you have that? Checked in Chrome and Safari, aligned okay for me

2022-09-26 08:15 UTC, gazpachu commented on system/react/src/components/Radio.ts
> +  --radio-size: 21px;
If the number looks weird, we should ask to make sure it's not a mistake. @hachi-studio is 21 in purpose?

2022-09-26 08:51 UTC, SimeonC commented on system/react/src/components/Radio.ts
> +export const Radio = styled.input<{ type?: 'radio' }>`
Missed that, I completely forgot defaultProps was a thing 🤣

2022-09-26 08:55 UTC, SimeonC commented
> > Looks like we have some weird centering issues of the dot, I think this may be because of the 21px that @gazpachu pointed out.
> 
> weird, @SimeonC where did you have that? Checked in Chrome and Safari, aligned okay for me

In chrome and safari 😅 also on chromatic (not sure if you can access this link) https://www.chromatic.com/test?appId=630da11410d64a1e5277962e&id=632c3cf2ab4869ac4fee5176

2022-09-26 09:32 UTC, SimeonC approved these changes

2022-09-26 09:37 UTC, staevs commented on system/react/src/components/Radio.ts
> +  --radio-size: 21px;
changed to 20px, as well that fixed @SimeonC issue with alignment

2022-09-27 00:01 UTC, gazpachu approved these changes

2022-09-27 00:01 UTC, merged