feat(tablekit-react): add button group component
tablecheck/tablekit pull request #123
Opened 2022-09-22 15:59 UTC by SashaShostyr

Resolves #101.

2022-09-28 00:37 UTC, SimeonC requested changes

2022-09-28 00:37 UTC, SimeonC commented on system/react/src/components/ButtonGroup.stories.tsx
> +      <ButtonGroup>
We need to be able to see all the following states in this story as well, have a look at the "variants" of checkbox/radio for an example. Note that in this case `active/hover/focus` only apply to one button so we would need a separate button group sample for each of `isSelected + active` and `!isSelected + active`

* `isSelected (default)`
* `isSelected + hover`
* `isSelected + active`
* `isSelected + focus`
* `!isSelected (default)`
* `!isSelected + hover`
* `!isSelected + active`
* `!isSelected + focus`

2022-09-28 00:37 UTC, SimeonC commented on system/react/src/components/ButtonGroup.ts
> +    height: 48px;
Better to rely on line-height and padding, don't set the height.

2022-09-28 00:37 UTC, SimeonC commented on system/react/src/components/ButtonGroup.ts
> +      z-index: 2;
I think this one should be `1` and the focus state should be `2` or the selected one would clip the focus ring of the focussed one.

2022-09-28 07:23 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.ts
> +      z-index: 2;
In that case there are other issues: 
<img width="178" alt="image" src="https://user-images.githubusercontent.com/19342294/192714766-ad279e08-096e-49ef-84bc-a558c8bb5b64.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/19342294/192714824-cb174f5b-171a-49ba-adbe-e9b4a1e3f925.png">

2022-09-28 07:55 UTC, SimeonC commented on system/react/src/components/ButtonGroup.ts
> +      z-index: 2;
😅 OK, there's lots of issues. I guess we need a solution where the focus ring is not clipped and the select is not clipped. Though I think that the second image might be acceptable. Need to double check with design team on this.

2022-09-28 10:37 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.stories.tsx
> +      <ButtonGroup>
Done and updated screenshots as well, rereview please

2022-09-28 10:37 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.ts
> +    height: 48px;
Done

2022-09-28 10:42 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.stories.tsx
> +      <ButtonGroup>
@xsanctom Is it fine to have such focus state on non-seleted items when selected item on the left (image 1) or right (image 2)?
<img width="186" alt="image" src="https://user-images.githubusercontent.com/19342294/192759255-3bb32115-f1bb-47a5-9b5a-7499bafb5c50.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/19342294/192759338-8fc433a6-4d82-4e63-a7b4-18f74efa76a0.png">

2022-09-30 01:32 UTC, SimeonC requested changes

2022-09-30 01:32 UTC, SimeonC commented on system/react/src/components/ButtonGroup.stories.tsx
> +    ))}
I like this! Can we move it to https://github.com/tablecheck/tablekit/blob/d19183884607ac3ac20c39e801ae56745c2d02ec/.storybook/preview.tsx#L156 so all stories get the headers as well? (I guess if `variants <= 1` we shouldn't show the header)

2022-09-30 01:32 UTC, SimeonC commented on system/react/src/components/ButtonGroup.stories.tsx
> +    )}
If we change the "combinations" here I think we can get a more concise output with less overlaps.

```tsx
const contentVariants = ['Default', 'Hover', 'Focus Selected', 'Focus Before', 'Focus After', 'Active'] as const;
```

(I recommend using a switch/case over if/else as typescript will error if you've missed a case in a switch)

```suggestion
    {[-1, 0, 1, 2].map((selectedIndex) => contentVariants.map((variant) => (
          <ButtonGroup>
            {['icon', 'text', 'icon+text'].map((type, index) => (
              <button
                /* eslint-disable-next-line react/no-array-index-key */
                key={`${selectedIndex}_${type}_${variant}_${index}`}
                type="button"
                data-pseudo={
                  // TODO - probably need to use a variable and a switch/case
                }
                data-selected={index === selectedIndex}
              >
                {['icon', 'icon+text'].includes(type) ? (
                  <FavoriteFilled size={20} />
                ) : null}
                {['text', 'icon+text'].includes(type) ? 'Text' : null}
              </button>
            ))}
          </ButtonGroup>
        ))
      ))
    )}
```

2022-09-30 07:03 UTC, SimeonC commented on system/react/src/components/ButtonGroup.stories.tsx
> +    ))}
Ah, that should be done in a separate PR. After this PR is merged can you raise another to move this headers logic to be global 🙇

2022-09-30 08:12 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.stories.tsx
> +    )}
@SimeonC Do you mean smth like this? 
![image](https://user-images.githubusercontent.com/19342294/193223951-71e81a03-13e2-4e4d-ad27-f894c3ba2f44.png)

2022-09-30 08:14 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.stories.tsx
> +    )}
I still using if/else though :sweat_smile:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/19342294/193224205-d801a46c-ef43-4dff-a105-ee5d58a7a509.png">

2022-09-30 08:52 UTC, SimeonC commented on system/react/src/components/ButtonGroup.stories.tsx
> +    )}
Yea I did mean something like that. I think hover and active should also have a case where they're only applied to one button which is why I suggested using `[-1, 0, 1, 2]` instead of `[0,1,2]` for the selected index. When `selectedIndex === -1` make the "middle" button active/hovered/focussed. That way we can check hover - non-hovered button interactions too.

2022-09-30 09:41 UTC, SashaShostyr commented on system/react/src/components/ButtonGroup.stories.tsx
> +    )}
Done, screenshots are updated, rereview please

2022-09-30 10:18 UTC, SimeonC requested changes
Looks good, can you just add a [chromatic width property](https://www.chromatic.com/docs/viewports#viewports-for-a-story) so the screenshots don't wrap.

![CleanShot 2022-09-30 at 19 15 32](https://user-images.githubusercontent.com/1085899/193249215-9ab5792d-43a8-4282-a5d2-c3a91b7e70a5.png)

2022-09-30 11:04 UTC, SashaShostyr commented
> Looks good, can you just add a [chromatic width property](https://www.chromatic.com/docs/viewports#viewports-for-a-story) so the screenshots don't wrap.

Done

2022-10-03 01:19 UTC, SimeonC approved these changes

2022-10-04 00:10 UTC, gazpachu approved these changes

2022-10-04 01:00 UTC, SimeonC commented
Ah, the CI is failing because you ignored the `DO NOT EDIT` comment at the top of `system/react/src/index.ts` - the file get's re-generated after build and the order has changed so the release fails.

2022-10-04 07:44 UTC, SashaShostyr commented
@SimeonC @gazpachu Reapprove please, had to rebase

2022-10-04 07:47 UTC, gazpachu approved these changes

2022-10-04 07:47 UTC, SimeonC approved these changes

2022-10-04 07:47 UTC, merged