feat(tablekit-icon-button) add icon button component
tablecheck/tablekit pull request #127
Opened 2022-09-27 06:23 UTC by hachi-studio

Fixed #102

2022-09-27 06:41 UTC, SimeonC commented on system/react/src/components/IconButton.stories.tsx
> +  parameters: { variants: variants.length, classySelector }
```suggestion
  parameters: { variants: variants.length, classySelector, classlessSelector }
```

2022-10-03 01:26 UTC, SimeonC approved these changes
Noticed a weirdness in focus outline and one of the states, but this also affects the normal button so I'll raise another ticket for that.

2022-10-04 00:31 UTC, gazpachu approved these changes

2022-10-04 07:09 UTC, SashaShostyr requested changes

2022-10-04 07:09 UTC, SashaShostyr commented on system/react/src/components/IconButton.stories.tsx
> +  parameters: { variants: variants.length, classySelector, classlessSelector }
Please make changes here as it will be broken now after merging this PR https://github.com/tablecheck/tablekit/pull/133

2022-10-04 07:15 UTC, SimeonC commented on system/react/src/components/IconButton.stories.tsx
> +  parameters: { variants: variants.length, classySelector, classlessSelector }
```suggestion
  parameters: { variants, classySelector, classlessSelector }
```

2022-11-09 07:10 UTC, closed without merging