feat(tablekit-react): add toggle component
tablecheck/tablekit pull request #129
Opened 2022-09-29 14:10 UTC by irmir

Completes #105

2022-09-30 06:59 UTC, SimeonC requested changes
![CleanShot 2022-09-30 at 15 51 25](https://user-images.githubusercontent.com/1085899/193209604-6a6c417c-499f-4990-b337-b64e7b743704.png)

Missing indeterminate state values, also size (see component and slack messages about that).

https://css-tricks.com/almanac/selectors/i/indeterminate/

2022-10-04 11:51 UTC, irmir commented
Thank you, done

2022-10-05 00:37 UTC, SimeonC commented
Turned on the "keep branches up to date" check - can you rebase and then I can check the Chromatic build.

2022-10-05 10:18 UTC, SimeonC requested changes

2022-10-05 10:18 UTC, SimeonC commented on system/react/src/components/Toggle.stories.tsx
> +          ref={refs2.current[index]}
This is simpler and needs less code.
```suggestion
          ref={(ref) => { if (ref) ref.indeterminate = true; }}
```

2022-10-05 19:44 UTC, irmir commented on system/react/src/components/Toggle.stories.tsx
> +          ref={refs2.current[index]}
thank you! done

2022-10-06 00:56 UTC, SimeonC approved these changes
Nice work!

2022-10-06 06:56 UTC, SimeonC reviewed
Let's hold off on merging this a little bit - we don't have focus styles in figma to finish off the design.

2022-10-07 10:55 UTC, SimeonC requested changes
![CleanShot 2022-10-07 at 19 47 38](https://user-images.githubusercontent.com/1085899/194537653-e1bfd35a-8ac0-41ec-add9-5706b5c74ac2.png)

Note that transparent border is wrong - it should be a darker purple. We also have the focus styles in figma so we can complete that.

2022-10-13 19:36 UTC, irmir commented
> Note that transparent border is wrong - it should be a darker purple. We also have the focus styles in figma so we can complete that.

@SimeonC I've added focus state but not sure about purple border. It uses transparent border in Figma not darker purple:
<img width="549" alt="Screenshot 2022-10-13 at 21 53 31" src="https://user-images.githubusercontent.com/59263605/195693124-17364ea3-7de4-4cfe-ba31-11bc53bf9019.png">

2022-10-14 00:43 UTC, SimeonC requested changes

2022-10-14 00:43 UTC, SimeonC commented on system/react/src/components/Toggle.ts
> +export const Toggle = styled.input<{ type?: 'checkbox' }>`
```suggestion
export const Toggle = styled.input<{ type: 'checkbox' }>`
```

This styling is only applicable to a checkbox so we should enforce it.

2022-10-14 01:16 UTC, SimeonC commented
> @SimeonC I've added focus state but not sure about purple border. It uses transparent border in Figma not darker purple:

Yes that's correct, there were some cases in the last version where the border was `transparent` - literally you could see the background colour through it.

This version looks correct.

2022-10-14 06:54 UTC, irmir commented on system/react/src/components/Toggle.ts
> +export const Toggle = styled.input<{ type?: 'checkbox' }>`
fixed

2022-10-19 16:52 UTC, irmir commented
@SimeonC looks like everything is ok in PR now, can you please have a look at audit checks?

2022-11-10 05:17 UTC, SimeonC approved these changes

2022-11-10 06:37 UTC, SashaShostyr approved these changes

2022-11-10 06:38 UTC, merged