fix(tablekit-react): update theme colors
tablecheck/tablekit pull request #139
Opened 2022-10-07 06:41 UTC by SashaShostyr

2022-10-07 09:56 UTC, SimeonC requested changes
Thanks for splitting the PRs, changes look good apart from one point.

2022-10-07 09:56 UTC, SimeonC commented on system/react/src/themeVariables/theme.ts
> +  --elevation-dark-small: 0 0 3px 0 rgba(255, 255, 255, 0.1);
We'll need some extra logic here to handle splitting this into the light and dark themes as it's not global anymore.

2022-10-10 10:07 UTC, SashaShostyr commented on system/react/src/themeVariables/theme.ts
> +  --elevation-dark-small: 0 0 3px 0 rgba(255, 255, 255, 0.1);
Updated, rereview please

2022-10-11 00:53 UTC, SimeonC approved these changes
Looks great! Thanks for doing the pr.

2022-10-11 01:03 UTC, wahidfarid approved these changes

2022-10-11 08:41 UTC, oFrederic approved these changes

2022-10-11 09:22 UTC, oFrederic approved these changes

2022-10-11 09:22 UTC, merged