fix: fixed input and button styles
tablecheck/tablekit pull request #146
Opened 2022-11-21 16:21 UTC by irmir

2022-11-21 16:23 UTC, irmir commented on system/react/src/components/Input.ts
> +  &[data-error='true'] {
maybe we should apply this pattern to `data-disabled` below?

2022-11-23 12:27 UTC, irmir commented on system/react/src/components/Button.ts
>    grid-gap: var(--spacing-l2);
<img width="248" alt="Screenshot 2022-11-21 at 19 14 20" src="https://user-images.githubusercontent.com/59263605/203546729-97a08d64-c796-49d4-b382-b3c64b4aab57.png">

2022-11-23 20:32 UTC, SashaShostyr commented on system/react/src/components/Input.ts
> +  &[data-error='true'] {
If we agree to use this here I think it should be changed for disabled state as well

2022-11-24 01:06 UTC, SimeonC commented on system/react/src/components/Input.ts
> +  &[data-error='true'] {
I think for consistency we should probably change this to use a variant name. I don't like the `='true'` in CSS selectors/html as that becomes slightly unexpected in react.

```suggestion
  &[data-variant='error'] {
```

2022-11-24 13:11 UTC, irmir commented on system/react/src/components/Input.ts
> +  &[data-error='true'] {
updated

2022-11-25 00:28 UTC, SimeonC requested changes

2022-11-25 00:28 UTC, SimeonC commented on system/react/src/components/Input.ts
> +  &[data-variant='stretch'] {
`data-stretch` is not the same as `data-variant` we can have `data-stretch data-variant="error"`.

`data-variant` should just be error and disabled.

2022-11-25 07:03 UTC, irmir commented on system/react/src/components/Input.ts
> +  &[data-variant='stretch'] {
fixed

2022-11-25 07:10 UTC, SashaShostyr commented on package-lock.json
> +      "optional": true,
Why we have changes in this file?

2022-11-25 07:10 UTC, SimeonC approved these changes

2022-11-25 08:11 UTC, irmir commented on package-lock.json
> +      "optional": true,
removed

2022-11-25 08:15 UTC, SashaShostyr submitted a review, later dismissed

2022-11-25 08:21 UTC, SimeonC approved these changes

2022-11-28 10:31 UTC, SimeonC approved these changes
I think these changes fixes #138 as well?

2022-11-28 10:33 UTC, SashaShostyr commented
> I think these changes fixes #138 as well?

Yes, should be fixed now

2022-11-28 11:30 UTC, xsanctom approved these changes

2022-11-29 01:38 UTC, merged