fix: add chip component
tablecheck/tablekit pull request #155
Opened 2023-01-24 04:22 UTC by hachi-studio

Adding chip component and stories

resolves: #104

2023-01-24 04:34 UTC, hachi-studio commented
@SimeonC I ended up doing this again as it's been a while from touching code and rebasing my old branch had me confused on a few things.

I think I mentioned a while ago but I am have an issue with showing the focus state in the story (works when you tab into it).

Let me know anything else I missed 🙇

2023-01-24 05:27 UTC, SimeonC requested changes
Look good, just one point on the CSS property usage that can be cleaned up.

2023-01-24 05:27 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +      calc(var(--padding-small-x) - 2px);
For this we should be able to go with just 2 variables and change the variables to get the change.
```suggestion
    --padding-x: 14px;
    --padding-y: 6px;
```

2023-01-24 06:02 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +  --padding-small-x: 14px;
Forgot to remove these unused props

2023-01-24 06:14 UTC, hachi-studio commented on system/react/src/components/Chip.tsx
> +  --padding-small-x: 14px;
Doh, pushed update 👍

2023-01-24 06:55 UTC, SimeonC submitted a review, later dismissed

2023-01-24 07:03 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +  border-radius: var(--border-radius-full);
I guess we can use just `50%` here

2023-01-24 07:08 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +  border-radius: var(--border-radius-full);
50% will give the wrong border - see here https://codepen.io/team/tablecheck/pen/BaProaQ/c6157b66c29fa8ec76f66cc847afaed2

2023-01-24 07:44 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +  border-radius: var(--border-radius-full);
I see, I guess it is fine to use `50%` only if width and height are the same

2023-01-24 07:45 UTC, SashaShostyr approved these changes

2023-01-31 08:47 UTC, SimeonC approved these changes

2023-01-31 09:50 UTC, SashaShostyr submitted a review, later dismissed

2023-01-31 09:57 UTC, SimeonC requested changes

2023-01-31 09:57 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +  }
Missing focus state for the chip

2023-02-06 07:31 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +  }
Added

2023-02-06 07:32 UTC, SashaShostyr submitted a review, later dismissed

2023-02-06 07:32 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +  }
![Uploading image.png…]()

2023-02-06 07:35 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +    }
Is there a reason we aren't using `box-shadow` here?

2023-02-06 07:40 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +    }
No, but we used such approach for all other components

2023-02-06 07:55 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +    }
Tried to use box-shadow, there are some issues on angles (more noticable with 10px box-shadow):
<img width="390" alt="image" src="https://user-images.githubusercontent.com/19342294/216915330-8dadb8aa-28df-4f8f-977e-df40af824b2e.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/19342294/216915560-b086a6b9-2f81-49bc-9a4d-c3dda949ea36.png">
I used such styles:
```
    outline: none;
    border-radius: var(--border-radius-full);
    box-shadow: -10px 0 var(--focus, hsla(219, 78.5%, 52.5%, 1)),
      0 -10px var(--focus, hsla(219, 78.5%, 52.5%, 1)),
      10px 0 var(--focus, hsla(219, 78.5%, 52.5%, 1)),
      0 10px var(--focus, hsla(219, 78.5%, 52.5%, 1));
```

2023-02-06 07:58 UTC, SimeonC commented on system/react/src/components/Chip.tsx
> +    }
Doesn't `box-shadow: 0 0 0 1px var(--focus);` work?

2023-02-06 08:03 UTC, SashaShostyr commented on system/react/src/components/Chip.tsx
> +    }
Ahh, right, it works 🤦

2023-02-06 08:04 UTC, SashaShostyr approved these changes

2023-02-06 08:50 UTC, SimeonC approved these changes

2023-02-06 08:58 UTC, merged