fix(tablekit-react): fix table row styles
tablecheck/tablekit pull request #183
Opened 2023-05-17 12:35 UTC by SashaShostyr

- Remove transition-in animation;
- Add cursor pointer on hover.

Relates to MOPS-1021, MOPS-1022.

2023-05-18 00:59 UTC, SimeonC requested changes

2023-05-18 00:59 UTC, SimeonC commented on system/core/src/components/Table.ts
> +      cursor: pointer;
By default, table rows should have the default cursor. Not all table rows are clickable.

2023-05-18 00:59 UTC, SimeonC commented on system/core/src/components/Table.ts
> +      transition: none;
Rather than setting the transition to none here - just remove the transition in `& tr`

2023-05-18 10:39 UTC, SashaShostyr commented on system/core/src/components/Table.ts
> +      transition: none;
I guess the request is to remove only transition-in animation not all. https://tablecheck.slack.com/archives/CCXQ4RAUE/p1682681708436729

2023-05-18 10:44 UTC, SashaShostyr commented on system/core/src/components/Table.ts
> +      cursor: pointer;
Updated

2023-05-19 05:18 UTC, SimeonC approved these changes

2023-05-19 07:36 UTC, nkgardose approved these changes

2023-05-19 07:57 UTC, merged