feat(tablekit-core): add `data-variant` as prop for `MenuItem`
tablecheck/tablekit pull request #196
Opened 2023-08-04 02:10 UTC by nkgardose

## Changes
* Added `data-variant` prop to `MenuItem`

## Screenshot
<img width="1468" alt="Screenshot 2023-08-03 at 19 12 12" src="https://github.com/tablecheck/tablekit/assets/17337106/9e8cbd46-6af0-4d9c-bb1d-c8878178957e">

2023-08-04 02:22 UTC, SimeonC requested changes
Have a look at how variants are done in the [`Alert` component](https://github.com/tablecheck/tablekit/blob/6630a53a2bc68c01d5ae3c1c0e4385c9baeb6464/system/core/src/components/Alert.ts#L71) and follow that.

2023-08-04 02:22 UTC, SimeonC commented on system/core/src/components/MenuItem.ts
> +  ...variantStylesObjects
Variants aren't stateStyles - these are essentially just for react-select integration.

2023-08-04 02:22 UTC, SimeonC commented on system/core/src/components/MenuItem.ts
> +  'data-variant'?: boolean;
```suggestion
  'data-variant'?: (typeof variants)[number];
```

2023-08-04 02:50 UTC, nkgardose commented on system/core/src/components/MenuItem.ts
> +  ...variantStylesObjects
I understand, thanks. I'll move it to base styles

2023-08-04 03:44 UTC, nkgardose commented on system/core/src/components/MenuItem.ts
> +  ...variantStylesObjects
Done

2023-08-04 03:44 UTC, nkgardose commented on system/core/src/components/MenuItem.ts
> +  'data-variant'?: boolean;
Done!

2023-08-04 06:02 UTC, SimeonC approved these changes

2023-08-07 01:40 UTC, k-baldauf approved these changes

2023-08-07 08:04 UTC, merged