feat(tablekit-core): add bare and disabled-bare, update info styling …
tablecheck/tablekit pull request #214
Opened 2023-11-29 05:59 UTC by k-baldauf

…in input-alert

Addresses https://github.com/tablecheck/tablekit/issues/192 but also switches `info` to its new styling (it was previously similar to what is now `bare`).

<img width="704" alt="The updated styling for the input-alert, showing info with a blue box, as well as the bare and bare-disabled styles" src="https://github.com/tablecheck/tablekit/assets/107082171/6ce496fa-4066-4f69-9fda-5f2144540f1e">

2023-11-29 06:12 UTC, SimeonC requested changes

2023-11-29 06:12 UTC, SimeonC commented on system/core/src/components/InputAlert.ts
> +  &[data-variant='bare-disabled'] {
Let's just call this `disabled`

2023-11-29 06:26 UTC, k-baldauf commented on system/core/src/components/InputAlert.ts
> +  &[data-variant='bare-disabled'] {
Done

2023-11-29 06:43 UTC, SimeonC approved these changes

2023-12-04 06:30 UTC, SashaShostyr approved these changes

2023-12-05 01:37 UTC, merged