chore: update dependencies for phone-input
tablecheck/tablekit pull request #22
Opened 2021-08-12 16:03 UTC by Findmitrey

Updated dependencies:
 - "input-format": "0.3.2" => "^0.3.6";
 - "libphonenumber-js": "1.9.19" => "^1.9.23";

Resolves #21

2021-08-12 17:29 UTC, SashaShostyr approved these changes

2021-08-12 17:36 UTC, SashaShostyr commented
Should be added `patch` label but I'm not sure

2021-08-12 17:49 UTC, wahidmagdy commented
I think this might need the `internal` label as there's no real difference for users of the package. CC: @SimeonC  for opinion

2021-08-12 17:50 UTC, wahidmagdy requested changes

2021-08-12 17:50 UTC, wahidmagdy commented on package.json
> +    "@emotion/react": "11.4.0",
was this line order manually done or was it the linter? is this change needed?

2021-08-13 01:55 UTC, SimeonC commented
Updating dependencies of a package.json is a patch if there's no code involved as it has "knock-on" effect. (excluding the root package.json)

So the commit should also be `fix(phone-input): ...` not `chore`. You can think of "internal" as "we shouldn't make a release for this" and dependency upgrades need a release.

2021-08-13 06:47 UTC, Findmitrey commented on package.json
> +    "@emotion/react": "11.4.0",
Thank you for the notification. Well, the linter did these changes because i do nothing manually in that file. I think we can keep these changes.

2021-08-16 06:33 UTC, wahidmagdy approved these changes

2021-08-16 07:06 UTC, gazpachu commented
I thought we were going to use the `lite` version. Why not?

2021-08-16 07:07 UTC, SimeonC approved these changes

2021-08-16 07:08 UTC, SimeonC commented
> I thought we were going to use the `lite` version. Why not?

Are you thinking of `yup-lite` in booking form not tablekit? There isn't a lite version of libphonenumber-js. Though you might be thinking about google-libphonenumber-js which is a bit bigger.

2021-08-16 09:10 UTC, merged