fix: disabled styles for Checkbox and Radio labels
tablecheck/tablekit pull request #222
Opened 2024-04-25 11:25 UTC by SashaShostyr

2024-04-26 00:10 UTC, SimeonC requested changes
This kind of change allows for incorrect semantics so we don't want to do that. Disabled styles on an input should only be applied when the pseudo element or prop is there.

2024-05-07 06:48 UTC, SimeonC commented on system/core/src/components/CheckboxRadioLabel.ts
> +  &[data-variant='disabled'] {
```suggestion
  &[data-variant='disabled'], &:has(input:disabled) {
```

Let's future proof this which will fix the unchanged checkbox/radio stories.

2024-05-14 11:41 UTC, SashaShostyr commented on system/core/src/components/CheckboxRadioLabel.ts
> +  &[data-variant='disabled'] {
Updated, thanks!

2024-05-15 01:08 UTC, SimeonC approved these changes

2024-05-16 04:53 UTC, SimeonC commented
I'll close this as this is included in #223 with the tests and everything to check it's working.

2024-05-16 04:53 UTC, closed without merging