fix: remove some packages that use react-spring
tablecheck/tablekit pull request #28
Opened 2021-08-15 11:53 UTC by gazpachu

- Removed footer and gallery
- Refactored spinner to avoid react-spring
- Modal dialog still uses react-spring (no peer dep)

Fixes #25

2021-08-15 12:12 UTC, wahidmagdy requested changes
Generally good, just worried about removing packages or introducing breaking changes in `Spinner`

2021-08-15 12:12 UTC, wahidmagdy commented on packages/package-namespace/src/PackageNamespace.ts
> -  Footer = 'footer',
Can we get confirmation that Footer/Gallery are not in use by any project and it's okay to delete them?

2021-08-15 12:12 UTC, wahidmagdy commented on packages/spinner/src/__tests__/index.tsx
>      });
`isCompleting` prop has been removed, so test name should be changed

2021-08-15 12:54 UTC, gazpachu commented on packages/package-namespace/src/PackageNamespace.ts
> -  Footer = 'footer',
They are being used in the Diner app, but it uses an old version of Tablekit. We won't be updating that app to use the latest version of TK. We are already working on a new Diner app

2021-08-15 12:58 UTC, gazpachu commented on packages/spinner/src/__tests__/index.tsx
>      });
fixed

2021-08-15 13:30 UTC, wahidmagdy approved these changes

2021-08-16 01:51 UTC, SimeonC commented on packages/modal-dialog/package.json
> -    "react-spring": ">=9.0.0-rc.3 <10"
Please leave this as a peer dependency.

2021-08-16 01:53 UTC, SimeonC commented on packages/spinner/src/Spinner.tsx
> -
Removing API on a component is a breaking change. Please change the label and commit to correctly reflect this.

2021-08-16 01:54 UTC, SimeonC requested changes
Left some comments that need addressing.

2021-08-16 02:05 UTC, gazpachu commented on packages/modal-dialog/package.json
> -    "react-spring": ">=9.0.0-rc.3 <10"
If we leave it as peer dependency, the main package.json will have to include the dep and therefore all projects using TK will have to use it as well, isn't it?

2021-08-16 02:26 UTC, gazpachu commented on packages/modal-dialog/package.json
> -    "react-spring": ">=9.0.0-rc.3 <10"
I'll have a look and see if we can remove it from modal-dialog as well

2021-08-16 06:31 UTC, SimeonC commented on packages/modal-dialog/package.json
> -    "react-spring": ">=9.0.0-rc.3 <10"
No that's incorrect. Dependencies are not used in the project unless they are imported, whether they are peer dependencies or not. We use a peer dependency to avoid duplicate versions and the issues that come with that.

This peer dependency means that the `modal-dialog` package requires you to install react-spring alongside it. It does not mean that if you are using a tablekit component that you need react-spring. This is the point of the monorepo, all the different packages have their own dependencies and requirements.

About bundling react-spring, if you don't use react-spring in the rest of your project and do `import('tablekit-modal-dialog')` then react-spring will be code split _with_ the modal dialog code.

2021-08-16 07:21 UTC, gazpachu commented on packages/modal-dialog/package.json
> -    "react-spring": ">=9.0.0-rc.3 <10"
Fixed

2021-08-16 07:21 UTC, gazpachu commented on packages/spinner/src/Spinner.tsx
> -
Fixed

2021-08-16 07:50 UTC, gazpachu commented
@SimeonC there seems to be a CI issue with the npm authentication

2021-08-16 08:40 UTC, SimeonC approved these changes

2021-08-17 04:43 UTC, merged