fix: intro page
tablecheck/tablekit pull request #29
Opened 2021-08-17 08:46 UTC by gazpachu

2021-08-17 08:58 UTC, SimeonC requested changes
This is not a fix - it's documentation, use the label `internal` and change the commit to "docs: ...`

2021-08-17 08:58 UTC, SimeonC commented on pages/Intro/Intro.stories.mdx
> +![coverage status](https://github.com/tablecheck/tablekit/badges/master/coverage.svg)
Neither of these exist and can be removed.

2021-08-18 00:14 UTC, gazpachu commented on pages/Intro/Intro.stories.mdx
> +![coverage status](https://github.com/tablecheck/tablekit/badges/master/coverage.svg)
fixed

2021-08-23 04:09 UTC, gazpachu commented
@SimeonC this should be ready to merge

2021-08-23 04:09 UTC, SimeonC approved these changes

2021-08-23 09:04 UTC, daniellizik approved these changes

2021-08-23 09:09 UTC, staevs approved these changes

2021-08-24 01:02 UTC, merged

2021-08-30 07:55 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/tablekit-alert@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-alert%401.0.1), [`@tablecheck/tablekit-avatar@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-avatar%401.0.1), [`@tablecheck/tablekit-badge@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-badge%401.0.1), [`@tablecheck/tablekit-banner@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-banner%401.0.1), [`@tablecheck/tablekit-button-group@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-button-group%401.0.1), [`@tablecheck/tablekit-button@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-button%401.0.1), [`@tablecheck/tablekit-calendar@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-calendar%401.0.1), [`@tablecheck/tablekit-checkbox@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-checkbox%401.0.1), [`@tablecheck/tablekit-free-icon-config@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-free-icon-config%401.0.1), [`@tablecheck/tablekit-icon@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-icon%401.0.1), [`@tablecheck/tablekit-inline-dialog@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-inline-dialog%401.0.1), [`@tablecheck/tablekit-input-button@1.0.2`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-input-button%401.0.2), [`@tablecheck/tablekit-input@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-input%401.0.1), [`@tablecheck/tablekit-item@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-item%401.0.1), [`@tablecheck/tablekit-language-selector@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-language-selector%401.0.1), [`@tablecheck/tablekit-logo@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-logo%401.0.1), [`@tablecheck/tablekit-modal-dialog@1.0.2`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-modal-dialog%401.0.2), [`@tablecheck/tablekit-panel@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-panel%401.0.1), [`@tablecheck/tablekit-password-field@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-password-field%401.0.1), [`@tablecheck/tablekit-phone-input@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-phone-input%401.0.1), [`@tablecheck/tablekit-pro-icon-config@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-pro-icon-config%401.0.1), [`@tablecheck/tablekit-radio@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-radio%401.0.1), [`@tablecheck/tablekit-select@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-select%401.0.1), [`@tablecheck/tablekit-sidenav@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-sidenav%401.0.1), [`@tablecheck/tablekit-table@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-table%401.0.1), [`@tablecheck/tablekit-tabs@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tabs%401.0.1), [`@tablecheck/tablekit-tag@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tag%401.0.1), [`@tablecheck/tablekit-textarea@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-textarea%401.0.1), [`@tablecheck/tablekit-toggle@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-toggle%401.0.1), [`@tablecheck/tablekit-tooltip@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tooltip%401.0.1), [`@tablecheck/tablekit-topnav@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-topnav%401.0.1) :rocket: