style(tablekit-input-button): changed appearance
tablecheck/tablekit pull request #32
Opened 2021-08-17 14:32 UTC by irmir

The checked button has solid background insted of outline
Text for all buttons is bold
Font-size is 16px (Typography.Body1)

completes #30

2021-08-18 00:10 UTC, gazpachu approved these changes

2021-08-18 02:28 UTC, SimeonC commented on packages/input-button/src/styled.ts
> +    color: white;
Hover and not-hover should not be the same background color, we need some indication of interactability.

2021-08-18 02:29 UTC, SimeonC requested changes
Note about 'hover' vs 'not-hover'. Also this needs to be a 'fix' or it won't be released.

2021-08-18 08:00 UTC, irmir commented on packages/input-button/src/styled.ts
> +    color: white;
Ok, I sent Sean variant with interactive hover

2021-08-19 01:32 UTC, gazpachu commented
@irmir what's the status of this PR? I thought this would be ready to merge today

2021-08-19 08:24 UTC, irmir commented on packages/input-button/src/styled.ts
> +    color: white;
Sean said me for now "hover over an active button it should not change"

2021-08-19 08:48 UTC, gazpachu approved these changes

2021-08-23 01:39 UTC, SimeonC approved these changes

2021-08-23 02:07 UTC, gazpachu approved these changes

2021-08-23 02:44 UTC, merged

2021-08-23 02:51 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/tablekit-input-button@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-input-button%401.0.1) :rocket: