feat(tablekit-modal-dialog): add maxWidth and maxHeight props
tablecheck/tablekit pull request #33
Opened 2021-08-17 19:39 UTC by irmir

completes #31

2021-08-18 00:05 UTC, gazpachu submitted a review, later dismissed

2021-08-18 03:06 UTC, SimeonC requested changes

2021-08-18 03:06 UTC, SimeonC commented on packages/modal-dialog/src/styled.ts
> +    typeof maxHeight === 'number'
For both max height and min height should be using the mediaQuery util from here https://github.com/tablecheck/tablekit/blob/main/packages/utils/src/mediaQuery.md. (There are other examples in TableKit)

Also, the base type shouldn't be `number` but `number | string` (wrapped in the Media Query type) because we could have `80vw` `95%` `12` (pixels)

2021-08-19 01:33 UTC, gazpachu commented
@irmir what's the status of this PR? I thought this would be ready to merge today

2021-08-20 03:26 UTC, SimeonC commented on packages/modal-dialog/src/styled.ts
> +    maxHeight?: MediaQuery<string | number>;
Rather than duplicating this here, add it to the pick. `Pick<BaseModalProps, 'height' | 'width' | 'isChromeless' | 'maxWidth' | 'maxHeight'>`. We use `Pick` in this case so that our types are always the same. After this fix I think we're good to go 👍

2021-08-20 09:58 UTC, irmir commented on packages/modal-dialog/src/styled.ts
> +    maxHeight?: MediaQuery<string | number>;
@SimeonC fixed!

2021-08-20 10:24 UTC, SimeonC approved these changes

2021-08-23 02:05 UTC, gazpachu approved these changes

2021-08-23 04:07 UTC, merged

2021-08-23 04:16 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/tablekit-modal-dialog@1.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-modal-dialog%401.0.1) :rocket: