fix(tablekit-button): calculates text color based on background luminance and changes hover color to 10% darker
tablecheck/tablekit pull request #67
Opened 2021-11-25 05:39 UTC by gazpachu

Completes 66

2021-11-25 06:27 UTC, SimeonC requested changes

2021-11-25 06:27 UTC, SimeonC commented on packages/button/src/themes.ts
> +      chroma(theme.colors.primary).luminance() < 5 ? 'white' : 'black',
Doing this prevents us from using cssVars so don't use chroma please.

If we need a 10% darker primary colour (if it's not already there) add it as a theme colour as it should be consistent across all packages.

Same for this luminance calculation, this should be done at app level, not in TableKit.

2021-11-25 11:58 UTC, gazpachu commented on packages/button/src/themes.ts
> +      chroma(theme.colors.primary).luminance() < 5 ? 'white' : 'black',
updated

2021-11-26 00:13 UTC, SimeonC commented on packages/button/src/themes.ts
> +      chroma(theme.colors.primary).luminance() < 5 ? 'white' : 'black',
The reason I was suggesting using `invertedText` rather than `buttonText` is because there's other situations where we'd need to put text on top of (in light mode) dark colours. It's a small tweak but I think this gives us more flexibility with the colour palette, for example the Contactless banner in TC Modules of Figma. https://www.figma.com/file/PCCFmEYNYBC9EkBDwgqMPw/Components?node-id=680%3A3447

2021-11-26 00:15 UTC, gazpachu commented on packages/button/src/themes.ts
> +      chroma(theme.colors.primary).luminance() < 5 ? 'white' : 'black',
Ahh, I totally forgot you suggested `invertedText`. Will replace it. Thx

2021-11-26 01:36 UTC, gazpachu commented on packages/button/src/themes.ts
> +      chroma(theme.colors.primary).luminance() < 5 ? 'white' : 'black',
Changed

2021-11-26 02:05 UTC, SimeonC commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
For dark theme colours this should be text colour from light mode, then we'd need to extend the primary button theme. I think having "invertedText" as white in dark mode would be confusing when being used.

```ts
// Dark theme
...buttonClassicTheme,
[Color.Primary]: {
  ...buttonClassicTheme[Color.Primary],
  text: ({ theme }) => theme.colors.text
}
```

2021-11-26 02:11 UTC, gazpachu commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
> For dark theme colours this should be text colour from light mode

Do you mean `invertedText: GRAY.L8`? I'm not following. Light mode text color is a dark grey

2021-11-26 05:53 UTC, SimeonC commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
Yes, that's what I mean. `invertedText` should be "inverted" according to the theme, so in light/classic inverted is light text on dark background, in dark mode it's dark text on light background.

The "theme level" colour names and the "button themes" don't need to be the same abstraction. "For part A of component B in theme C, use named theme colour D".

2021-11-26 05:58 UTC, gazpachu commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
Default buttons text color should be white for both, classic and dark themes because the default background color for buttons is the same for both, classic and dark. This is why a thought `buttonText` would have less ramifications. I didn't get your last paragraph.

2021-11-26 06:00 UTC, gazpachu commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
changed

2021-11-26 06:17 UTC, gazpachu commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
updated also button dark theme

2021-11-26 06:34 UTC, SimeonC approved these changes

2021-11-26 06:35 UTC, SimeonC commented on packages/theme/src/palettes.ts
> +  invertedText: 'white',
Awesome, thanks!

2021-11-26 06:48 UTC, Findmitrey approved these changes

2021-11-26 06:50 UTC, merged

2021-11-26 07:02 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/tablekit-alert@3.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-alert%403.0.1), [`@tablecheck/tablekit-avatar@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-avatar%402.0.1), [`@tablecheck/tablekit-badge@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-badge%402.0.1), [`@tablecheck/tablekit-banner@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-banner%402.0.1), [`@tablecheck/tablekit-button-group@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-button-group%402.0.1), [`@tablecheck/tablekit-button@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-button%402.0.1), [`@tablecheck/tablekit-calendar@3.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-calendar%403.0.1), [`@tablecheck/tablekit-checkbox@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-checkbox%402.0.1), [`@tablecheck/tablekit-enzyme@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-enzyme%402.0.1), [`@tablecheck/tablekit-free-icon-config@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-free-icon-config%402.0.1), [`@tablecheck/tablekit-icon@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-icon%402.0.1), [`@tablecheck/tablekit-inline-dialog@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-inline-dialog%402.0.1), [`@tablecheck/tablekit-input-button@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-input-button%402.0.1), [`@tablecheck/tablekit-input@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-input%402.0.1), [`@tablecheck/tablekit-item@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-item%402.0.1), [`@tablecheck/tablekit-language-selector@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-language-selector%402.0.1), [`@tablecheck/tablekit-logo@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-logo%402.0.1), [`@tablecheck/tablekit-modal-dialog@3.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-modal-dialog%403.0.1), [`@tablecheck/tablekit-panel@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-panel%402.0.1), [`@tablecheck/tablekit-password-field@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-password-field%402.0.1), [`@tablecheck/tablekit-phone-input@3.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-phone-input%403.0.1), [`@tablecheck/tablekit-pro-icon-config@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-pro-icon-config%402.0.1), [`@tablecheck/tablekit-radio@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-radio%402.0.1), [`@tablecheck/tablekit-select@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-select%402.0.1), [`@tablecheck/tablekit-sidenav@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-sidenav%402.0.1), [`@tablecheck/tablekit-spinner@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-spinner%402.0.1), [`@tablecheck/tablekit-table@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-table%402.0.1), [`@tablecheck/tablekit-tabs@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tabs%402.0.1), [`@tablecheck/tablekit-tag@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tag%402.0.1), [`@tablecheck/tablekit-textarea@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-textarea%402.0.1), [`@tablecheck/tablekit-theme@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-theme%402.0.1), [`@tablecheck/tablekit-toggle@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-toggle%402.0.1), [`@tablecheck/tablekit-tooltip@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-tooltip%402.0.1), [`@tablecheck/tablekit-topnav@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-topnav%402.0.1), [`@tablecheck/tablekit-typography@2.0.1`](https://github.com/tablecheck/tablekit/releases/tag/%40tablecheck/tablekit-typography%402.0.1) :rocket: